C
C
C
      SUBROUTINE   PROBARY
C
C     + + + PURPOSE + + +
C     ?????
C
C     + + + COMMONS + + +
      INCLUDE 'cprobn.inc'
      INCLUDE 'cjm.inc'
C
C     + + + LOCAL VARIABLES + + +
      INTEGER BYR,BMO,BDY,EYR,EMO,EDY,UVWY,BWY,EWY
      INTEGER PARMCA,JULDAT(12)
      INTEGER OPEAKMO,OPEAKDY
      INTEGER NUMSPC,STRJUL,ENDJUL,NYR,PEAKMO,PEAKDY
      INTEGER OLOWMO,OLOWDY,OFLWMO(5),OFLWDY(5)
      INTEGER LOWMO,LOWDY,FLWMO(5),FLWDY(5)
      INTEGER MYR(365),MO(365),MDY(365)
      INTEGER   IWY,IMO,IDY,STATCA,IDUM
      INTEGER   K, I, J
      REAL FLWVAL(5),PRO(365),ORO(365),PP(365),PREDFW,OBSERV,PEAR
      REAL AVAFLW,PROBAY(100,7,2)
      REAL      PEAK, OPEAK, OVAFLW, PEKJUL, OPEKJUL
      CHARACTER*2 IC
      CHARACTER*3 FLWTYP(5)
C
C     + + + DATA INITIALIZATIONS + + +
      DATA JULDAT/0,31,59,90,120,151,181,212,243,273,304,334/           JKM10/85
C
C     + + + INPUT FORMATS + + +
   10 FORMAT(A2,10X,A3,F5.0)
C
C     + + + OUTPUT FORMATS + + +
   20 FORMAT(I5,14F10.1)
   30 FORMAT(1X,3I5,1X,F8.1,F5.2)
   40 FORMAT (' ',' IN PROBARY BYRPR = ',I5,' EYRPR = ',I5)             KD1291
   50 FORMAT (' ',' IN PROBARY MYR MO MDY PRO PP ORO',3I5,3F8.1)        KD1291
C
C     + + + END SPECIFICATIONS + + +
C
      ENDFILE 65
      REWIND(65)
      PEAK=0.0
      PEAKMO=EMOPR
      PEAKDY=EDYPR
      AVAFLW=0.0
      OBSERV=0.0
      PREDFW=0.0
      LOWMO=EMOPR
      LOWDY=EDYPR
      OPEAK=0.0
      OPEAKMO=EMOPR
      OPEAKDY=EDYPR
      OVAFLW=0.0
      OLOWMO=EMOPR
      OLOWDY=EDYPR
      DO 75 K=1,5
        FLWMO(K)=EMOPR
        FLWDY(K)=EDYPR
   75 CONTINUE
      DO 85 K=1,5
        OFLWMO(K)=EMOPR
        OFLWDY(K)=EDYPR
   85 CONTINUE
      IF (DEBUG.EQ.0) GO TO 3000
      WRITE (70,40) BYRPR,EYRPR
 3000 NUMSPC=0
      DO 200 I=1,5
        READ(55,10,END=250) IC,FLWTYP(I),FLWVAL(I)
        IF(FLWTYP(I).EQ.'END') GO TO 250
        IF (DEBUG.EQ.0) GO TO 4000
        PRINT *,' FLWTYP = ',FLWTYP(I),' FLWVAL = ',FLWVAL(I)
 4000   NUMSPC=I
  200 CONTINUE
  250 STRJUL=JULDAT(BMOPR)+BDYPR
      ENDJUL=JULDAT(EMOPR)+EDYPR
      NYR=EYRPR-BYRPR+1
      DO 500 J=1,NYR
        DO 285 I=STRJUL,ENDJUL
  275     READ (65,END=290) MYR(I),MO(I),MDY(I),PRO(I),PP(I),ORO(I)
          IF (DEBUG.EQ.1) WRITE (70,50) MYR(I),MO(I),MDY(I),
     *         PRO(I),PP(I),ORO(I)
  285   CONTINUE
  290   DO 300 I=STRJUL,ENDJUL
          IF (DEBUG.EQ.0) GO TO 1020
          WRITE (70,50) MYR(I),MO(I),MDY(I),PRO(I),PP(I),ORO(I)
 1020     PREDFW=PREDFW+PRO(I)
          OBSERV=OBSERV+ORO(I)
          IF(PEAK.GT.PRO(I)) GO TO 295
          PEAK=PRO(I)
          PEAKMO=MO(I)
          PEAKDY=MDY(I)
  295     IF(OPEAK.GT.ORO(I)) GO TO 300
          OPEAK=ORO(I)
          OPEAKMO=MO(I)
          OPEAKDY=MDY(I)
  300   CONTINUE
        PEKJUL=JULDAT(PEAKMO)+PEAKDY
        OPEKJUL=JULDAT(OPEAKMO)+OPEAKDY
        IF (DEBUG.EQ.1) WRITE(70,*) PEAK,PEAKMO,PEAKDY,PEKJUL
        IF (DEBUG.EQ.1) WRITE(70,*) OPEAK,OPEAKMO,OPEAKDY,OPEKJUL
  105   IF(NUMSPC.EQ.0) GO TO 401
        DO 400 I=STRJUL,ENDJUL
          DO 325 K=1,NUMSPC
            IF (DEBUG.EQ.1) WRITE(70,*) NUMSPC,FLWTYP(K),FLWVAL(K),
     *           PRO(I),ORO(I)
            IF(FLWTYP(K).NE.'  A') GO TO 310
            IF((PRO(I)-FLWVAL(K)).LE.0.0) GO TO 305
            AVAFLW=AVAFLW+(PRO(I)-FLWVAL(K))
  305       IF((ORO(I)-FLWVAL(K)).LE.0.0) GO TO 310
            OVAFLW=OVAFLW+(ORO(I)-FLWVAL(K))
  310       IF(PEKJUL.GT.(JULDAT(MO(I))+MDY(I))) GO TO 320
            IF(FLWTYP(K).NE.'  L') GO TO 315
            IF(LOWMO.LE.EMOPR.AND.LOWDY.LT.EDYPR) GO TO 315
            IF (DEBUG.EQ.1) WRITE(70,*) LOWMO,EMOPR
            IF((PRO(I)-FLWVAL(K)).GT.0.0) GO TO 315
            LOWMO=MO(I)
            LOWDY=MDY(I)
  315       IF(FLWTYP(K).NE.'  F') GO TO 320
            IF(FLWMO(K).LE.EMOPR.AND.FLWDY(K).LT.EDYPR) GO TO 320
            IF (DEBUG.EQ.1) WRITE(70,*) FLWMO(K),EMOPR
            IF((PRO(I)-FLWVAL(K)).GT.0.0) GO TO 320
            FLWMO(K)=MO(I)
            FLWDY(K)=MDY(I)
  320       IF(OPEKJUL.GT.(JULDAT(MO(I))+MDY(I))) GO TO 325
            IF(FLWTYP(K).NE.'  L') GO TO 323
            IF(OLOWMO.LE.EMOPR.AND.OLOWDY.LT.EDYPR) GO TO 323
            IF((ORO(I)-FLWVAL(K)).GT.0.0) GO TO 323
            OLOWMO=MO(I)
            OLOWDY=MDY(I)
  323       IF(FLWTYP(K).NE.'  F') GO TO 325
            IF(OFLWMO(K).LE.EMOPR.AND.OFLWDY(K).LT.EDYPR) GO TO 325
            IF((ORO(I)-FLWVAL(K)).GT.0.0) GO TO 325
            OFLWMO(K)=MO(I)
            OFLWDY(K)=MDY(I)
  325     CONTINUE
  400   CONTINUE
  401   PROBAY(J,1,1)=PREDFW*1.9835
        PROBAY(J,1,2)=ENDJUL-STRJUL+1
        PROBAY(J,2,1)=PEAK
        PROBAY(J,2,2)=PEKJUL
        IF(PROBAY(J,2,2).GT.365) PROBAY(J,2,2)=PROBAY(J,2,2)-365
        IF(NUMSPC.EQ.0) GO TO 475
        DO 450 K=1,NUMSPC
          IF(FLWTYP(K).NE.'  A') GO TO 405
          PROBAY(J,2+K,1)=AVAFLW*1.9835
          PROBAY(J,2+K,2)=FLWVAL(K)
  405     IF(FLWTYP(K).NE.'  L') GO TO 410
          PROBAY(J,2+K,1)=FLWVAL(K)
          PROBAY(J,2+K,2)=JULDAT(LOWMO)+LOWDY
  410     IF(FLWTYP(K).NE.'  F') GO TO 450
          PROBAY(J,2+K,1)=FLWVAL(K)
          PROBAY(J,2+K,2)=JULDAT(FLWMO(K))+FLWDY(K)
          FLWMO(K)=EMOPR
          FLWDY(K)=EDYPR
  450   CONTINUE
  475   LOWMO=EMOPR
        LOWDY=EDYPR
        PEAKMO=EMOPR
        PEAKDY=EDYPR
        PEAK=0.0
        PREDFW=0.0
        OBSERV=0.0
        AVAFLW=0.0
  500 CONTINUE
  600 CONTINUE
      CLOSE(65)
      CLOSE(60)
      CLOSE(55)
      DO 700 I=1,NYR
        WRITE(70,20) BYRPR+I-1,((PROBAY(I,J,K),K=1,2),J=1,7)
  700 CONTINUE
      CLOSE(70)
      RETURN
      END
