C
C
C
      SUBROUTINE   SNOCOV
C
C     + + + PURPOSE + + +
C     ?????
C
C     + + + COMMONS + + +
      INCLUDE 'call.inc'
      INCLUDE 'csno.inc'
      INCLUDE 'csnop.inc'
      INCLUDE 'csncv.inc'
C
C     + + + LOCAL VARIABLES + + +
      INTEGER   IRU, KRV, IDX, JDX
      REAL      PW, AI, DIVX, PCTY, FRAC, AF, DIFX, DIFY
C
C     + + + INTRINSICS + + +
      INTRINSIC   FLOAT
C
C     + + + OUTPUT FORMATS + + +
C9000 FORMAT(3X,'JDY-IRU-PW-AI-I-J-ASC-IA-PK-SC',2I5,2F5.2,2I5,         KD1291
C    1F5.2,I5,2F5.2)
C
C     + + + END SPECIFICATIONS + + +
C
      DO 500 IRU=1,NRU
      KRV=KSDC(IRU)                                                     GL0386
      PW=PWEQV(IRU)
      ASC(IRU)=SCA(KRV,11)                                              GL0386
      IF(PW.LE.0.) GO TO 490
C       SET AREAL INDEX AI
      IF(PW.GT.PST(IRU)) PST(IRU)=PW
      AI=PST(IRU)
      IF(AIMX(IRU).LT.AI) AI=AIMX(IRU)
      IF(PW.GE.AI) GO TO 450
      IF(NSW(IRU).EQ.0) GO TO 100
      IF(IASW(IRU).GT.0) GO TO 80
C       RECEIVED NEW SNOW ON PARTIAL SNOW COVER
      IASW(IRU)=1
      ASCSV(IRU)=ASC(IRU)
      PKSV(IRU)=PW-PSN(IRU)
   80 SCRV(IRU)=PW-(.25*PSN(IRU))
      GO TO 490
  100 IF(IASW(IRU).EQ.0) GO TO 200
      IF(PW.GT.SCRV(IRU)) GO TO 490
      IF(PW.LT.PKSV(IRU)) GO TO 120
C       NEW SNOW NOT MELTED BACK TO ORIGINAL PARTIAL AREA
      DIFX=SCA(KRV,11)-ASCSV(IRU)                                       GL0386
      PCTY=(PW-PKSV(IRU))/(SCRV(IRU)-PKSV(IRU))
      ASC(IRU)=ASCSV(IRU)+(PCTY*DIFX)
      GO TO 490
C       PWEQV BACK TO VALUE BEFORE NEW SNOW
  120 IASW(IRU)=0
C       INTERPOLATE ALONG SNOW AREA DEPLETION CURVE
  200 FRAC=PW/AI
      IDX=10.*(FRAC+.2)
      JDX=IDX-1
      AF=FLOAT(JDX-1)
      DIFY=(FRAC*10.)-AF
  250 DIFX=SCA(KRV,IDX)-SCA(KRV,JDX)
      ASC(IRU)=SCA(KRV,JDX)+(DIFY*DIFX)
      GO TO 490
  450 IASW(IRU)=0
  490 CONTINUE
C 490 WRITE(72,9000) JLDY,IRU,PW,AI,IDX,JDX,ASC(IRU),IASW(IRU),
C    1PKSV(IRU),SCRV(IRU)
  500 CONTINUE
      RETURN
      END
