C     version information: versn = char*64
      VERSN = '@(#)PRMS -- Precipitation-Runoff Modeling System'
      VERSN = '@(#)PRMS -- USGS WRIR 83-4238, Leavesley, Lichty,'
      VERSN = '@(#)PRMS -- Troutman, and Saindon'
      VERSN = '@(#)PRMS -- Contact Kate Flynn, kmflynn@usgs.gov'
      VERSN = '@(#)PRMS -- Version 2.0 1994/05/01 (HASS tape 2)'
      VERSN = '@(#)PRMS -- Version 2.1 1996/01/17 (HASS tape 3)'
